# Generated by Django 5.0.3 on 2024-03-05 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('net', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('net', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Flowspec',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('srcip', models.CharField(blank=True, max_length=50)),
                ('srcprt', models.IntegerField(blank=True, default=-1)),
                ('dstip', models.CharField(max_length=50)),
                ('dstprt', models.IntegerField(blank=True, default=-1)),
                ('protocol', models.CharField(blank=True, max_length=10)),
                ('action', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('net', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowspecs', to='fnm_watui.network')),
            ],
            options={
                'unique_together': {('net', 'srcip', 'srcprt', 'dstip', 'dstprt', 'protocol')},
            },
        ),
    ]
