# Generated by Django 5.0.3 on 2024-03-21 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnm_watui', '0002_alter_flowspec_net'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowspec',
            name='net',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowspecs', to='fnm_watui.network'),
        ),
    ]
