# Generated by Django 5.0.3 on 2024-03-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnm_watui', '0004_alter_flowspec_net'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowspec',
            name='net',
            field=models.CharField(max_length=20),
        ),
    ]
